"""Added age

Revision ID: 91189f234331
Revises: 239f65c3e57e
Create Date: 2017-03-24 10:52:45.115394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91189f234331'
down_revision = '239f65c3e57e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
